// Loaded by Tailwind v4 through `@config` in src/index.css. The theme is
// GENERATED by `crunk tokens` from crunk.toml -- edit crunk.toml, not this.
import theme from "./tailwind.theme.json";

export default {
  theme: { extend: theme },
};
